<a href="https://colab.research.google.com/github/priyanshdatyal/TensorFlow-Notes-With-Code/blob/main/Topic_7_TensorManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### Tensor Manipulation or Operations

---



In [34]:
import tensorflow as tf

Basixc Wale  

In [35]:
tensorForOp = tf.constant([[1,2],[3,4]])
tensorForOp

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [36]:
# Add +
tensorForOp+5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 7],
       [8, 9]], dtype=int32)>

In [37]:
# Substraction -
tensorForOp-2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1,  0],
       [ 1,  2]], dtype=int32)>

In [38]:
# Multiplication
tensorForOp*2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [40]:
# Division /
tensorForOp/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5, 1. ],
       [1.5, 2. ]])>

In [39]:
# In-built Functions

tf.multiply(tensorForOp,3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  6],
       [ 9, 12]], dtype=int32)>