<a href="https://colab.research.google.com/github/priyanshdatyal/TensorFlow-Notes-With-Code/blob/main/Topic_21_SavingTheModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Saving the Model

In [3]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

Saving the model allows us to use our models wherever we want 

1. Android
2. WebApp
3. Software
4. Or Anywhere


There are two main formats to save our model
1. Saveodel format : Allow us to format the model even after saving it by loading it again
2. The HTF5 format : Heirarichal Data Format

### SaveModel Format


In [8]:
X = tf.range(-100,100,4)
y=X+10

lengthTrain =len(X)*0.8
X_train = X[:int(lengthTrain)]
X_test = X[int(lengthTrain):]


y_train = y[:int(lengthTrain)]
y_test = y[int(lengthTrain):]

tf.random.set_seed(42)
model = tf.keras.Sequential([
                  tf.keras.layers.Dense(1,input_shape=[1]),
                  tf.keras.layers.Dense(1,input_shape=[1])
])
model.compile(
    loss=tf.keras.losses.mae,
    optimizer=tf.keras.optimizers.Adam(lr=0.045),
    metrics=["mae"])

# model.summary()
model.fit(X_train,y_train,epochs=225,verbose=0)
y_predicted=model.predict(X_test)
y_predicted,tf.metrics.mean_absolute_error(y_test,tf.squeeze(tf.constant(y_predicted)))

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


(array([[ 70.01865 ],
        [ 74.01486 ],
        [ 78.01107 ],
        [ 82.00728 ],
        [ 86.003494],
        [ 89.9997  ],
        [ 93.995926],
        [ 97.99213 ],
        [101.98835 ],
        [105.984566]], dtype=float32),
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009468079>)

In [4]:
model.save("SavingTheModelFirst")

INFO:tensorflow:Assets written to: SavingTheModelFirst/assets


###Hierarichal Saving

In [6]:
model.save("SavingTheModelFirstInHDF5.h5")

## Loading the Saved Format

In [11]:
loadModel = tf.keras.models.load_model('/content/SavingTheModelFirst')
loadModel

In [12]:
loadModel.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
 dense_1 (Dense)             (None, 1)                 2         
                                                                 
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 1)                 2         
                                                                 
 dense_5 (Dense)             (None, 1)                 2         
                                                                 
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


#### So the loadee model and trained model has same summary so our model was saved perfectly. Below is one more test

In [14]:
modelPrediction = model.predict(y_test)
savedModelPrediction = loadModel.predict(y_test)

In [15]:
modelPrediction == savedModelPrediction

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

There we go