<a href="https://colab.research.google.com/github/priyanshdatyal/TensorFlow-Notes-With-Code/blob/main/Topic_8_MatrixMultiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import tensorflow as tf

#### Matrix Multiplication

---



In [16]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[11,12],[13,14]])

# Matmul is a function reprensting Matrix Multplication in 
# Tensflow.LinearAlgebra.MatrixMultiplication => tf.linalg.matmul

'''
  Matrix Multplication here in this exaple goes like 
  [
      [1*11+2*13   1*12+2*14],
      [3*11+4*13   3*12+4*14]]
  ]
'''

tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[37, 40],
       [85, 92]], dtype=int32)>

In [17]:
a*b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 24],
       [39, 56]], dtype=int32)>

In [18]:
'''
  Notice one thing that the multiplication give diffrent results because

  a*b means directly

  [
    [a00*b00  a01*b01],
    [a10*b10  a11*b11]
  ]

'''

'\n  Notice one thing that the multiplication give diffrent results because\n\n  a*b means directly\n\n  [\n    [a00*b00  a01*b01],\n    [a10*b10  a11*b11]\n  ]\n\n'

In [19]:
# Matrix Multiplication using python operator

a@b


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[37, 40],
       [85, 92]], dtype=int32)>

In [21]:
m1 = tf.constant([[1,2],[3,4],[5,6]])
m2 = tf.constant([[11,12],[13,14],[15,16]])

m1 @ m2

InvalidArgumentError: ignored

In [ ]:
'''

  Highlight : 
    Matrix Multiplication for same dims will only work if it is sqare matrix

    Why ?
      The resultant matrix has dims of inner dims 

      For e.g. 

      A is x X y
      B is w X z

      Resultant of A @ B will be w X y

'''