<a href="https://colab.research.google.com/github/priyanshdatyal/TensorFlow-Notes-With-Code/blob/main/Topic_12_TensorAggregation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Aggregation in Tensors

In [76]:
import tensorflow as tf
import numpy as np

Positional Min and Max 

In [77]:
tf.random.set_seed(33)
minmax = tf.random.uniform(shape=[5,5])
minmax

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.33143902, 0.21867776, 0.0160141 , 0.2876439 , 0.79751086],
       [0.21710753, 0.6433041 , 0.36862898, 0.50054467, 0.71634173],
       [0.42660952, 0.53803957, 0.22099257, 0.81026185, 0.57730436],
       [0.85869336, 0.3830887 , 0.10151541, 0.40971458, 0.53684866],
       [0.675125  , 0.8787942 , 0.2530595 , 0.5888306 , 0.8912947 ]],
      dtype=float32)>

In [78]:
tf.argmax(minmax)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([3, 4, 1, 2, 4])>

### Simplified

In [79]:
tf.random.set_seed(33)
minmax = tf.random.uniform(shape=[50])
minmax

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.33143902, 0.21867776, 0.0160141 , 0.2876439 , 0.79751086,
       0.21710753, 0.6433041 , 0.36862898, 0.50054467, 0.71634173,
       0.42660952, 0.53803957, 0.22099257, 0.81026185, 0.57730436,
       0.85869336, 0.3830887 , 0.10151541, 0.40971458, 0.53684866,
       0.675125  , 0.8787942 , 0.2530595 , 0.5888306 , 0.8912947 ,
       0.8457856 , 0.3994583 , 0.24162519, 0.581491  , 0.74078023,
       0.7363901 , 0.96084607, 0.713277  , 0.6095383 , 0.2995093 ,
       0.5917554 , 0.891641  , 0.24231768, 0.38349473, 0.9355582 ,
       0.33619452, 0.6970371 , 0.41257358, 0.51162803, 0.5456264 ,
       0.5786649 , 0.37017047, 0.28624272, 0.07297945, 0.32062662],
      dtype=float32)>

In [80]:
tf.argmax(minmax),minmax[tf.argmax(minmax)]

(<tf.Tensor: shape=(), dtype=int64, numpy=31>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.96084607>)

In [81]:
tf.reduce_max(minmax)

<tf.Tensor: shape=(), dtype=float32, numpy=0.96084607>

Now Min

In [84]:
tf.argmin(minmax),minmax[tf.argmin(minmax)]

(<tf.Tensor: shape=(), dtype=int64, numpy=2>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0160141>)

In [83]:
tf.reduce_min(minmax)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0160141>

### Sqeezing the Tensor 

In [93]:
tensorUnsqueezed = tf.constant(tf.random.uniform(shape=[250]),shape=[1,1,1,1,250])
tensorUnsqueezed

<tf.Tensor: shape=(1, 1, 1, 1, 250), dtype=float32, numpy=
array([[[[[0.95492065, 0.21872997, 0.7677808 , 0.9726474 , 0.84337306,
           0.77971196, 0.1659218 , 0.39122605, 0.47791672, 0.5908618 ,
           0.15626991, 0.5698248 , 0.63537204, 0.19131398, 0.3045088 ,
           0.03077245, 0.6876521 , 0.10798144, 0.37167406, 0.8372042 ,
           0.3698783 , 0.02974355, 0.45547402, 0.83659434, 0.23944008,
           0.7429966 , 0.3924365 , 0.4987495 , 0.01042569, 0.69050443,
           0.13724029, 0.5452088 , 0.9311893 , 0.9620658 , 0.5193043 ,
           0.507077  , 0.01250613, 0.3300202 , 0.30394948, 0.2840767 ,
           0.9531692 , 0.5825106 , 0.9618553 , 0.7676648 , 0.5472481 ,
           0.16979933, 0.34554875, 0.429469  , 0.05787849, 0.8127135 ,
           0.44637883, 0.40979528, 0.7079793 , 0.9830241 , 0.38128793,
           0.6790546 , 0.03306043, 0.361449  , 0.22849023, 0.57489634,
           0.22083938, 0.97565866, 0.94104195, 0.19369638, 0.584887  ,
           0.91437

In [95]:
tensorSqueezed = tf.squeeze(tensorUnsqueezed)
tensorSqueezed

<tf.Tensor: shape=(250,), dtype=float32, numpy=
array([0.95492065, 0.21872997, 0.7677808 , 0.9726474 , 0.84337306,
       0.77971196, 0.1659218 , 0.39122605, 0.47791672, 0.5908618 ,
       0.15626991, 0.5698248 , 0.63537204, 0.19131398, 0.3045088 ,
       0.03077245, 0.6876521 , 0.10798144, 0.37167406, 0.8372042 ,
       0.3698783 , 0.02974355, 0.45547402, 0.83659434, 0.23944008,
       0.7429966 , 0.3924365 , 0.4987495 , 0.01042569, 0.69050443,
       0.13724029, 0.5452088 , 0.9311893 , 0.9620658 , 0.5193043 ,
       0.507077  , 0.01250613, 0.3300202 , 0.30394948, 0.2840767 ,
       0.9531692 , 0.5825106 , 0.9618553 , 0.7676648 , 0.5472481 ,
       0.16979933, 0.34554875, 0.429469  , 0.05787849, 0.8127135 ,
       0.44637883, 0.40979528, 0.7079793 , 0.9830241 , 0.38128793,
       0.6790546 , 0.03306043, 0.361449  , 0.22849023, 0.57489634,
       0.22083938, 0.97565866, 0.94104195, 0.19369638, 0.584887  ,
       0.91437995, 0.9243853 , 0.9486395 , 0.8888906 , 0.7763299 ,
       0.53490