<a href="https://colab.research.google.com/github/priyanshdatyal/TensorFlow-Notes-With-Code/blob/main/Topic_5_InformationAboutTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Fetch Information about tensors

---



In [14]:
import tensorflow as tf

In [ ]:
'''
  Attributes of a tensor                                   Execution

    - Rank                                                 tensor.ndim                                                          
    - Shape                                                tensor.shape
    - Axis or Dimension                                    tensor[x],tensor[:,x]  //where x is the index
    - Size                                                 tf.size(tensor)

'''

In [16]:
experimentalVariable = tf.zeros(shape=(2,3,4,5))
experimentalVariable

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [17]:
# Attributes of experimentalVariable

experimentalVariable.ndim,tf.size(experimentalVariable),experimentalVariable.shape


(4, <tf.Tensor: shape=(), dtype=int32, numpy=120>, TensorShape([2, 3, 4, 5]))

In [18]:
print("Try all methods on this. For eg \n")
print(f"Dimensions is(No. of variables in shape) : {experimentalVariable.ndim}")

Try all methods on this. For eg 

Dimensions is(No. of variables in shape) : 4
