<a href="https://colab.research.google.com/github/priyanshdatyal/TensorFlow-Notes-With-Code/blob/main/Topic_10_DorProductTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Dor Products in Tensors

In [10]:
import tensorflow as tf


In [11]:
# Lets try to get the basic first

matOne = tf.constant([[1,2],[3,4],[5,6]])
matTwo = tf.constant([[11,12],[13,14],[15,16]])

In [12]:
 # So before everything Le'ts try and see diff between transponse and reshape


print(f"Matrix 2 is \n{matTwo}")
print(f"\nMatrix 2 reshaped is \n{tf.reshape(matTwo,shape=(2,3))}")
print(f"\nMatrix 2 transposed is \n {tf.transpose(matTwo)}")

Matrix 2 is 
[[11 12]
 [13 14]
 [15 16]]

Matrix 2 reshaped is 
[[11 12 13]
 [14 15 16]]

Matrix 2 transposed is 
 [[11 13 15]
 [12 14 16]]


In [ ]:
# So its obvious that they will produce diffrent results for Matrix and Dot Multiplication 

In [ ]:
'''
  Highlight : So whenever performing multiplication and rules are not being obeyed for multiplication
  we will transpose the matrix instead of reshaping it to avoid data disruption and get satisfactory results  
'''

In [ ]:
# NBow we are on dot production 

In [14]:
tf.tensordot(matOne,matTwo,axes=2)

<tf.Tensor: shape=(), dtype=int32, numpy=301>

In [15]:
tf.tensordot(matOne,matTwo,axes=1)

InvalidArgumentError: ignored

In [ ]:
# It happened with dot multiplication as well so now we will use the masterstroke
# b y transposing any of two matrix

In [16]:
tf.tensordot(matOne,tf.transpose(matTwo),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 35,  41,  47],
       [ 81,  95, 109],
       [127, 149, 171]], dtype=int32)>

In [17]:
tf.tensordot(tf.transpose(matOne),matTwo,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[125, 134],
       [164, 176]], dtype=int32)>