<a href="https://colab.research.google.com/github/priyanshdatyal/TensorFlow-Notes-With-Code/blob/main/Topic_6_MoreInformationAboutTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import tensorflow as tf

In [17]:
experimentalVariable = tf.zeros(shape=(2,3,4,5))
experimentalVariable

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [18]:
#Indexing in the Tensors

experimentalVariable[:1,:1,:3,:2]

<tf.Tensor: shape=(1, 1, 3, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.],
         [0., 0.]]]], dtype=float32)>

In [19]:
#Indexing Except (Lets take exaple of index 2 )


experimentalVariable[:1,:,:3,:2]

<tf.Tensor: shape=(1, 3, 3, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]], dtype=float32)>

In [20]:
# Indexing for last element

experimentalVariable[:,:,:,-1]

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [21]:
# Same as above with simple exaple

experimentalVariableTwo=tf.constant([[1,2],[3,4]])

print(f" With : \n {experimentalVariableTwo[:,:-1]}")
print(f" Without : \n {experimentalVariableTwo[:,-1]}")

 With : 
 [[1]
 [3]]
 Without : 
 [2 4]


In [22]:
# Notice the diffrence in above examples

In [23]:
# Increase the rank/Axis of tensor by one

experimentalVariableTwo=experimentalVariableTwo[...,tf.newaxis]
experimentalVariableTwo

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [24]:
# Alternative Ways 

tf.expand_dims(experimentalVariableTwo,axis=0)

# Try with axis-1 and 2 as well 

<tf.Tensor: shape=(1, 2, 2, 1), dtype=int32, numpy=
array([[[[1],
         [2]],

        [[3],
         [4]]]], dtype=int32)>

In [25]:

tf.expand_dims(experimentalVariableTwo,axis=1)

<tf.Tensor: shape=(2, 1, 2, 1), dtype=int32, numpy=
array([[[[1],
         [2]]],


       [[[3],
         [4]]]], dtype=int32)>

In [26]:

tf.expand_dims(experimentalVariableTwo,axis=-1)

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[1]],

        [[2]]],


       [[[3]],

        [[4]]]], dtype=int32)>