<a href="https://colab.research.google.com/github/priyanshdatyal/TensorFlow-Notes-With-Code/blob/main/Topic_12_TensorAggregation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Aggregation in Tensors

In [55]:
import tensorflow as tf
import numpy as np

In [56]:
# Absolute

matrix = tf.constant([[1,-2],[-3,4]])
tf.abs(matrix)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

Some other methods now

In [57]:
matric = tf.constant(np.random.randint(1,100,size=40))
matric

<tf.Tensor: shape=(40,), dtype=int64, numpy=
array([ 9, 25, 99, 91, 72, 87, 39, 17, 28, 18, 79, 71, 27, 63, 80, 91, 75,
       10, 39, 39, 60, 62, 78, 21, 41, 37, 16, 80, 51, 74, 98, 77, 35, 19,
       21, 73,  4, 45, 72,  1])>

In [65]:
# Operations

print(f"\nMinimum is {tf.reduce_min(matric)}")
print(f"\nMaximum is {tf.reduce_max(matric)}")
print(f"\nSum is {tf.reduce_sum(matric)}")
print(f"\nMean is {tf.reduce_mean(matric)}")
print(f"\nStandard Deviation is {tf.math.reduce_std(matric,axis=0)}")
print(f"\nVariance is {tf.math.reduce_variance(matric)}")




Minimum is 1

Maximum is 99

Sum is 2024

Mean is 50


TypeError: ignored

In [66]:

matric=tf.cast(matric,dtype=tf.complex64)

print(f"\nStandard Deviation is {tf.math.reduce_std(matric,axis=0)}")
print(f"\nVariance is {tf.math.reduce_variance(matric)}")



Standard Deviation is 28.870227813720703

Variance is 833.4900512695312


In [ ]:
'''
  STD and Variance only for Either complex or real numbers in tensorflow 
'''