<a href="https://colab.research.google.com/github/priyanshdatyal/TensorFlow-Notes-With-Code/blob/main/Topic_13_OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

####  One Hot Encoding

In [10]:
import tensorflow as tf

In [19]:
sampleList = [0,1,2,3]

tf.one_hot(sampleList,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [13]:

tf.one_hot(sampleList,depth=5)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

In [14]:

tf.one_hot(sampleList,depth=15)

<tf.Tensor: shape=(3, 15), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)>

In [21]:
# Custpoom keys


tf.one_hot(sampleList,depth=4,on_value="ON",off_value="OFF")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ON', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'ON', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON']], dtype=object)>

Square log and Root
___

In [22]:
sensor = tf.range(0,10)
tf.square(sensor)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [23]:
tf.sqrt(sensor)

InvalidArgumentError: ignored

In [24]:
# So lets make it float
tf.sqrt(tf.cast(sensor,dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.        , 0.99999994, 1.4142134 , 1.7320508 , 1.9999999 ,
       2.236068  , 2.4494896 , 2.6457512 , 2.828427  , 3.        ],
      dtype=float32)>

In [25]:
tf.math.log(sensor)

InvalidArgumentError: ignored

In [27]:

tf.math.log(tf.cast(sensor,dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 ,
       1.7917595, 1.9459102, 2.0794415, 2.1972246], dtype=float32)>