<a href="https://colab.research.google.com/github/priyanshdatyal/TensorFlow-Notes-With-Code/blob/main/Topic_14_TensorWithNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

####  One Hot Encoding

In [34]:
import tensorflow as tf
import numpy as np


##### Tensors and NumPy

In [35]:
# Cross coversion of type

tfc = tf.constant(np.array([3.,7.,10.]))
tfc

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [36]:
nfc = np.array(tfc)
nfc

array([ 3.,  7., 10.])

In [38]:
# Or 

tfc.numpy(),type(tfc.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

# Diffrence dtypes for same functionality

In [39]:
nA = tf.constant(np.array([1,2]))
tA = tf.constant([1,2])

#checking the types 

nA.dtype,tA.dtype

(tf.int64, tf.int32)

In [40]:
nA = tf.constant(np.array([1.,2.]))
tA = tf.constant([1.,2.])

#checking the types 

nA.dtype,tA.dtype

(tf.float64, tf.float32)