<a href="https://colab.research.google.com/github/priyanshdatyal/TensorFlow-Notes-With-Code/blob/main/Topic_3_RandomTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
###### Random 

import tensorflow as tf

In [64]:
#Lets get started making random tensors

randomOne = tf.random.Generator.from_seed(42)
randomOne=randomOne.normal(shape=(2,2))
randomTwo = tf.random.Generator.from_seed(42)
randomTwo=randomTwo.normal(shape=(2,2))

randomOne,randomTwo,randomOne==randomTwo


(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True]])>)

In [65]:
# Wait What? What the hell is wrong with random number generator
# Allow me explain, So we are using from_seed as 42 which sets the seed to 42

'''
 What's Seed and why?
 
  The answer is for Reproducability. In some studies or Researches the reliablity of data is important to to assure 
  the high degree of reliability on repition of experiment we have from_seed

'''

# Try it out set value of from seed to values other than 42 and see what happens.
'''
   Highlight - These are not random - These are preudo random

'''

"\n What's Seed and why?\n \n  The answer is for Reproducability. In some studies or Researches the reliablity of data is important to to assure \n  the high degree of reliability on repition of experiment we have from_seed\n\n"

In [66]:
# Lets Shuffle

#Original
original_tensor = tf.constant([[1,2],
                              [3,4],
                              [5,6]])

#Original shuffle 1
shuffled_tensor = tf.random.shuffle(original_tensor)
#Original shuffle 2
shuffled_tensor2 = tf.random.shuffle(original_tensor)
#Shuffled shuffle 1
shuffle_the_shuffled=tf.random.shuffle(shuffled_tensor)


original_tensor,shuffled_tensor,shuffled_tensor2,shuffle_the_shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[5, 6],
        [1, 2],
        [3, 4]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[5, 6],
        [3, 4],
        [1, 2]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [1, 2],
        [5, 6]], dtype=int32)>)

In [67]:
# Chalo Lets see something weird
tf.random.shuffle(original_tensor,seed=(42))

'''
  Highlight : This will give diffrent result everytime

  This one is a operation level seed
''' 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [68]:
tf.random.set_seed(42)
tf.random.shuffle(original_tensor)

'''
 Highlight : This will give same result everytime no matter what

 This one is a global level seed

'''

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>