<a href="https://colab.research.google.com/github/priyanshdatyal/TensorFlow-Notes-With-Code/blob/main/Topic_9_MatrixMultiplicationSolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import tensorflow as tf

#### Matrix Multiplication

---



In [25]:
m1 = tf.constant([[1,2],[3,4],[5,6]])
m2 = tf.constant([[11,12],[13,14],[15,16]])

# m1 @ m2

In [ ]:
'''
  So the logic to generalise in square matrix was to make inner axis equal

  So lets try now 

'''

In [28]:
tf.reshape(m2,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [30]:
m1 @ tf.reshape(m2,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  42,  45],
       [ 89,  96, 103],
       [139, 150, 161]], dtype=int32)>

In [ ]:
# Hey It worked 

In [32]:
# Transpose 

tf.transpose(m1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [ ]:
'''
  Multiplication using transpose is diffrent from that using reshape

  Now DIY
'''